sudo: required
services:
  - docker

before_install:
  - docker build -t dinesh/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true dinesh/docker_react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker_react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-692913427579"
  bucket_path: "docker_react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
